@set allusersprofile=c:\programdata
@set appdata=c:\users\hello\appdata\roaming
@set chocolateyinstall=c:\programdata\chocolatey
@set chocolateylastpathupdate=132309706360926815
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set complus_installroot=
@set complus_version=
@set computername=desktop-fmiu0su
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set homedrive=c:
@set homepath=\users\hello
@set include=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\atlmfc\include;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include;c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared;c:\program files (x86)\windows kits\10\include\10.0.17763.0\um;c:\program files (x86)\windows kits\10\include\10.0.17763.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.17763.0\cppwinrt
@set intellij idea=c:\program files\jetbrains\intellij idea 2020.1.2\bin
@set lib=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\lib\x64;c:\program files (x86)\windows kits\10\lib\10.0.17763.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.17763.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\lib\x64;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.17763.0;c:\program files (x86)\windows kits\10\references\10.0.17763.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\hello\appdata\local
@set logonserver=\\desktop-fmiu0su
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set number_of_processors=8
@set onedrive=c:\users\hello\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2017\community\msbuild\15.0\bin\roslyn;c:\program files (x86)\microsoft visual studio\2017\community\team tools\performance tools\x64;c:\program files (x86)\microsoft visual studio\2017\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\\x64;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x64;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\microsoft visual studio\2017\community\\msbuild\15.0\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x64;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x86;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\common files\oracle\java\javapath;c:\oraclexe\app\oracle\product\11.2.0\server\bin;c:\programdata\oracle\java\javapath;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\git\cmd;c:\mingw\bin;c:\program files\cmake\bin;c:\program files\apache-maven-3.6.3\bin;c:\program files\nodejs\;c:\program files\java\jdk1.8.0_241\bin;c:\programdata\chocolatey\bin;w:\revelation\revelation\misc;w:\revelation\revelation\src;c:\mingw\mingw32\bin;c:\program files\putty\;c:\program files\matlab\r2020a\bin;c:\users\hello\appdata\local\programs\python\python38\scripts\;c:\users\hello\appdata\local\programs\python\python38\;c:\users\hello\appdata\local\programs\python\python38-32\scripts\;c:\users\hello\appdata\local\programs\python\python38-32\;c:\users\hello\appdata\local\microsoft\windowsapps;c:\users\hello\appdata\roaming\npm;c:\programdata\chocolatey\lib\mingw\tools\install\mingw64\bin;c:\users\hello\appdata\local\programs\microsoft vs code\bin;c:\program files\jetbrains\intellij idea 2020.1.2\bin;c:\texlive\2020\bin\win32;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\ninja
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\hello\appdata\local\microsoft\visualstudio\15.0_c9fdf475\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 142 stepping 10, genuineintel
@set processor_level=6
@set processor_revision=8e0a
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_vs2017=c:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvsbuildtools_installdir_vs2017=c:\program files (x86)\microsoft visual studio\2017\community
@set quartus_rootdir=c:\altera\13.0sp1\quartus
@set sessionname=console
@set sopc_kit_nios2=c:\altera\13.0sp1\nios2eds
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\hello\appdata\local\temp
@set tmp=c:\users\hello\appdata\local\temp
@set ucrtversion=10.0.17763.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-fmiu0su
@set userdomain_roamingprofile=desktop-fmiu0su
@set username=hello
@set userprofile=c:\users\hello
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2017\community\vc\redist\msvc\14.16.27012\
@set vctoolsversion=14.16.27023
@set visualstudiodir=c:\users\hello\documents\visual studio 2017
@set visualstudioedition=microsoft visual studio community 2017
@set visualstudioversion=15.0
@set vs150comntools=c:\program files (x86)\microsoft visual studio\2017\community\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=15.9.23
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\community\
@set vslang=1033
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.17763.0;c:\program files (x86)\windows kits\10\references\10.0.17763.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.17763.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.17763.0\
@set windowssdkversion=10.0.17763.0\
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x64;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x86;c:\program files (x86)\microsoft visual studio\2017\community\common7\tools;c:\program files (x86)\microsoft visual studio\2017\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\common files\oracle\java\javapath;c:\oraclexe\app\oracle\product\11.2.0\server\bin;c:\programdata\oracle\java\javapath;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\git\cmd;c:\mingw\bin;c:\program files\cmake\bin;c:\program files\apache-maven-3.6.3\bin;c:\program files\nodejs\;c:\program files\java\jdk1.8.0_241\bin;c:\programdata\chocolatey\bin;w:\revelation\revelation\misc;w:\revelation\revelation\src;c:\mingw\mingw32\bin;c:\program files\putty\;c:\program files\matlab\r2020a\bin;c:\users\hello\appdata\local\programs\python\python38\scripts\;c:\users\hello\appdata\local\programs\python\python38\;c:\users\hello\appdata\local\programs\python\python38-32\scripts\;c:\users\hello\appdata\local\programs\python\python38-32\;c:\users\hello\appdata\local\microsoft\windowsapps;c:\users\hello\appdata\roaming\npm;c:\programdata\chocolatey\lib\mingw\tools\install\mingw64\bin;c:\users\hello\appdata\local\programs\microsoft vs code\bin;c:\program files\jetbrains\intellij idea 2020.1.2\bin;c:\texlive\2020\bin\win32

@call "cl.exe" @"C:\Atlas\Atlas\ImGuiLayer.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1